module.exports = {
	content: ['./src/**/*.{html,js,svelte,ts}'],
	plugins: [require('daisyui')],
	daisyui: {
		themes: [
			'light',
			'dark',
			'cupcake',
			'corporate',
			'synthwave',
			'cyberpunk',
			'valentine',
			'halloween',
			'forest',
			'aqua',
			'lofi',
			'fantasy',
			'wireframe',
			'luxury',
			'dracula',
			'autumn',
			'business',
			'acid',
			'night',
			'coffee',
			'winter',
			'nord',
			'sunset',
		  {
			butter: {
			  "color-scheme": "light",
			  "base-100": "hsl(64, 6%, 14%)",
			  neutral: "#8e8d80",
			  primary: "#c6c3ac",
			  secondary: "#f1edd2",
			  accent: "#9747d8",
			  info: "#96c1da",
			  success: "#8ad89f",
			  warning: "#d8c46c",
			  error: "#d86c6c",
			  default: "#c6c3ac",
			},
		  },
		  {
			aura: {
			  "color-scheme": "dark",
			  "base-100": "#15141b",
			  neutral: "#edecee",
			  primary: "#a277ff",
			  secondary: "#61ffca",
			  accent: "#f694ff",
			  info: "#82e2ff",
			  success: "#49f488",
			  warning: "#ffca85",
			  error: "#ff6767",
			  default: "#edecee",
			},
		  },
		  {
			tokyo: {
			  "color-scheme": "dark",
			  "base-100": "#1a1b26",
			  neutral: "#9aa5ce",
			  primary: "#c0caf5",
			  secondary: "#cfc9c2",
			  accent: "#bb9af7",
			  info: "#7aa2f7",
			  success: "#9ece6a",
			  warning: "#e0af68",
			  error: "#f7768e",
			  default: "#9aa5ce",
			},
		  },
		],
	  },
};